/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/D2xG6wUtWrS
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"

export function Chat() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center h-14 border-b px-4 lg:h-20 bg-gray-100/40 dark:bg-gray-800/40 border-gray-200 dark:border-gray-800">
        <div className="items-center grid grid-cols-[auto_1fr] gap-4 lg:gap-8">
          <div className="flex items-center gap-4 lg:gap-8">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="">Acme Inc</span>
            </Link>
          </div>
          <nav className="items-center flex gap-4 ml-auto">
            <Link
              className="font-medium text-gray-900  transition-all hover:text-gray-900 dark:text-gray-50 dark:hover:text-gray-50"
              href="#"
            >
              Home
            </Link>
            <Link
              className="font-medium text-gray-500  transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Features
            </Link>
            <Link
              className="font-medium text-gray-500  transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Pricing
            </Link>
            <Link
              className="font-medium text-gray-500  transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#"
            >
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4 md:ml-auto lg:gap-8">
            <Button size="sm" variant="outline">
              New Project
            </Button>
            <Button className="rounded-full" size="icon" variant="ghost">
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32"
              />
              <span className="sr-only">Toggle user menu</span>
            </Button>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 lg:py-24">
          <div className="text-center">
            <div className="grid max-w-3xl gap-4 lg:gap-8 mx-auto items-center lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4 lg:space-y-8">
                <h1 className="text-3xl font-bold tracking-tight lg:text-5xl">Chat with Lithium AI</h1>
                <p className="text-gray-500 xl:text-xl md:max-w-[500px] lg:mx-auto dark:text-gray-400">
                  Ask questions, get support, and learn more about our platform. Our AI assistant is here to help you
                  24/7.
                </p>
              </div>
              <div className="flex flex-col gap-4">
                <div className="grid gap-2">
                  <Label className="sr-only" htmlFor="name">
                    Message
                  </Label>
                  <Textarea
                    className="min-h-[200px] border-gray-200 dark:border-gray-800"
                    id="name"
                    placeholder="Type your message..."
                  />
                </div>
                <Button size="lg">Send</Button>
              </div>
            </div>
          </div>
        </section>
        <section className="border-t py-12 lg:py-24">
          <div>
            <div className="grid gap-6 lg:gap-12 md:grid-cols-2">
              <div className="flex flex-col gap-4">
                <h2 className="text-3xl font-bold tracking-tight">How can I help you today?</h2>
                <p className="text-gray-500 xl:text-xl md:max-w-[500px] lg:mx-auto dark:text-gray-400">
                  Our AI assistant is trained to answer your questions. Whether you need help with onboarding, want to
                  learn more about our features, or have a technical issue, the Lithium AI is here to help.
                </p>
              </div>
              <div className="grid gap-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Chat with Lithium AI</CardTitle>
                    <CardDescription>
                      Ask questions, get support, and learn more about our platform. Our AI assistant is here to help
                      you 24/7.
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="p-0">
                    <div className="grid gap-4 p-4">
                      <div className="text-sm font-medium">How can I help you today?</div>
                      <div className="text-right text-sm text-gray-500 dark:text-gray-400">Typing...</div>
                      <div className="text-sm">
                        Hi there! I'm Lithium, your virtual assistant. How can I help you today?
                      </div>
                    </div>
                    <div className="border-t">
                      <form className="flex items-center gap-2 p-2">
                        <PlaneIcon className="w-6 h-6" />
                        <Input className="flex-1 min-w-0" id="message" placeholder="Type your message..." />
                        <Button type="submit">Send</Button>
                      </form>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}


function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  )
}
